name: Python Greetings

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  install-pip-deps:
    runs-on: [self-hosted, windows]
    steps:
      - uses: actions/checkout@v6

      - name: Install deps step
        uses: ./.github/actions/install-deps

  deploy-to-dev:
    needs: install-pip-deps
    runs-on: [self-hosted, windows]
    steps:
      - uses: actions/checkout@v6

      - name: Deploy DEV
        uses: ./.github/actions/deploy
        with:
          env-name: dev
          port: 7001

  tests-on-dev:
    needs: deploy-to-dev
    runs-on: [self-hosted, windows]
    steps:
      - uses: actions/checkout@v6

      - name: Test DEV
        uses: ./.github/actions/test
        with:
          env-name: dev

  deploy-to-stg:
    needs: tests-on-dev
    runs-on: [self-hosted, windows]
    steps:
      - uses: actions/checkout@v6

      - name: Deploy STG
        uses: ./.github/actions/deploy
        with:
          env-name: stg
          port: 7002

  tests-on-stg:
    needs: deploy-to-stg
    runs-on: [self-hosted, windows]
    steps:
      - uses: actions/checkout@v6

      - name: Test STG
        uses: ./.github/actions/test
        with:
          env-name: stg

  deploy-to-preprod:
    needs: tests-on-stg
    runs-on: [self-hosted, windows]
    steps:
      - uses: actions/checkout@v6

      - name: Deploy PREPROD
        uses: ./.github/actions/deploy
        with:
          env-name: preprod
          port: 7003

  tests-on-preprod:
    needs: deploy-to-preprod
    runs-on: [self-hosted, windows]
    steps:
      - uses: actions/checkout@v6

      - name: Test PREPROD
        uses: ./.github/actions/test
        with:
          env-name: preprod

  deploy-to-prod:
    needs: tests-on-preprod
    runs-on: [self-hosted, windows]
    steps:
      - uses: actions/checkout@v6

      - name: Deploy PROD
        uses: ./.github/actions/deploy
        with:
          env-name: prod
          port: 7004

  tests-on-prod:
    needs: deploy-to-prod
    runs-on: [self-hosted, windows]
    steps:
      - uses: actions/checkout@v6

      - name: Test PROD
        uses: ./.github/actions/test
        with:
          env-name: prod
